package exceptions;

public class TryFinally {

	public static void main(String[] args) {
		try{
			System.out.println("in try Block");
		}
		finally{
			System.out.println("In finally");
		}

	}

}
